version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL:postgres://eacassecasse:@Pas1sword23@database:5432/ukuphi_db
      - NODE_ENV=development

  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: eacassecasse
      POSTGRES_PASSWORD: @Pas1sword23
      POSTGRES_DB: ukuphi_db