services:
  ukuphi-app-pg:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    shm_size: 512mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql

  ukuphi-app-redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data/var/lib/redis/data

volumes:
  postgres_data:
  redis_data: