name: Deploy Backend Ukhupi App

on:
  push:
    branches:
      - main
      - backend-development

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      STAGING_SERVER: ${{ secrets.STAGING_IP }}
      PRODUCTION_SERVER: ${{ secrets.PRODUCTION_IP }}
      DEPLOY_SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
      USER: ${{ secrets.DEPLOY_USER }}
      REPO_URL: ${{ secrets.REPO_URL }}
      APP_NAME: ukuphi-app
      BASE_PATH: /var/www/ukuphi-app

    strategy:
      matrix:
        environment: [staging, production] 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Determine Deployment Path
        id: deployment_path
        run: |
          if [[ "${{ matrix.environment }}" == "production" ]]; then
            echo "path=production" >> $GITHUB_ENV
            echo "host=${{ env.PRODUCTION_SERVER }}" >> $GITHUB_ENV
          elif [[ "${{ matrix.environment }}" == "staging" ]]; then
            echo "path=staging" >> $GITHUB_ENV
            echo "host=${{ env.STAGING_SERVER }}" >> $GITHUB_ENV
          else
            echo "Skipping deployment for this combination."
            exit 0
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup SSH Key for authentication
        run: |
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
  
          if [ ! -f ~/.ssh/id_rsa ]; then
            echo "${{ env.DEPLOY_SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
          else
            echo "SSH private key id_rsa already exists, skipping overwrite"
          fi
  
          if [ ! -f ~/.ssh/droplet_id_rsa ]; then
            echo "${{ env.DEPLOY_SSH_KEY }}" | base64 -d > ~/.ssh/droplet_id_rsa
            chmod 600 ~/.ssh/id_rsa
          else
            echo "SSH private key droplet_id_rsa already exists, skipping overwrite"
          fi

          # Add the host dynamically to known_hosts
          if [ -z "$host" ]; then
            echo "Error: Host is not set. Check Determine Deployment Path step."
            exit 1
          fi
  
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          ssh-keyscan -H "$host" >> ~/.ssh/known_hosts
          echo "SSH key setup completed."
  
      - name: Debug Runner Directory
        run: |
          echo "Listing all directories..."
          ls -la
          echo "Listing backend directory..."
          ls -la backend || echo "Backend directory not found"

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          cd backend
          npm install

      - name: Build Application
        run: |
          cd backend
          npm run build

      - name: Deploy Application
        run: |
          echo "Starting deployment to ${{ matrix.environment }}..."
          ssh -o StrictHostKeyChecking=no ${{ env.USER }}@$host << 'EOF'
            # Define environment paths
            APP_PATH="${{ env.BASE_PATH }}/${{ matrix.environment }}/backend"
            REPO_PATH="$APP_PATH/releases/$(date +'%Y%m%d%H%M%S')"
            BACKEND_PATH="$REPO_PATH/backend"

            # Create necessary directories
            mkdir -p $APP_PATH/releases
            mkdir -p $APP_PATH/shared

            # Clone or pull the repository
            if [ ! -d "$REPO_PATH" ]; then
              git clone ${{ env.REPO_URL }} $REPO_PATH
            else
              cd $REPO_PATH
              git fetch origin
            fi

            # Checkout the appropriate branch based on the environment
            cd $REPO_PATH
            if [[ "${{ matrix.environment }}" == "staging" ]]; then
              git checkout backend-development
              git pull origin backend-development
            else
              git checkout main
              git pull origin main
            fi

            # Ensure backend folder exists
            if [ ! -d "$BACKEND_PATH" ]; then
              echo "Error: Backend folder not found in the repository."
              exit 1
            fi

            cp $APP_PATH/shared/.env $BACKEND_PATH/.env
            chmod 600 $BACKEND_PATH/.env
            chown -R ${{ env.USER }}:${{ env.USER }} $BACKEND_PATH/.env

            # Add .env to .gitignore if it's not already present
            if ! grep -q ".env" $BACKEND_PATH/.gitignore; then
              echo ".env" >> $BACKEND_PATH/.gitignore
              echo ".env added to .gitignore"
            else
              echo ".env already in .gitignore, skipping..."
            fi

            # Set the 'current' symlink to the new release
            ln -sfn $BACKEND_PATH $APP_PATH/current

            # Install dependencies and start/restart the application
            cd $APP_PATH/current/backend
            npm cache clean --force
            timeout 300 npm install --omit=dev --loglevel=error || {
              echo "npm install timeout or failure. Retrying with cache cleanup..."
              npm cache clean --force
              npm install --omit=dev --loglevel=error
            }

            # Managing process with pm2
            PROCESS_NAME="ukuphi-backend-${{ matrix.environment }}"

            if pm2 list | grep -q "$PROCESS_NAME"; then
              pm2 delete "$PROCESS_NAME" || echo "Failed to delete pm2 process. Proceeding..."
            fi
            pm2 start dist/index.js --name "$PROCESS_NAME" --update-env || pm2 restart "$PROCESS_NAME" --update-env
          EOF
          